Repository OpenWaterAnalytics/EPANET, pull requests merged in 2019-02, with the labels that each got.

#384 Add support to build for default and python library targets
  .travis.yml
  CMakeLists.txt
  appveyor.yml
  include/epanet2.def
  include/epanet2.h
  include/epanet2_2.h
  include/epanet_py.h
  run/CMakeLists.txt
  src/epanet_py.c
Labels: enhancement

#385 Add new function to get and set title strings
  include/epanet2.bas
  include/epanet2.h
  include/epanet2.vb
  include/epanet2_2.h
  src/epanet.c
  src/epanet2.c
  win_build/WinSDK/epanet2.def
Labels: Net builder

#390 Adding reg tests to coverage
  .travis.yml
  tools/run-nrtest.sh
Labels: testing

#391 Simplify command line arguments for reg test helper scripts
  appveyor.yml
  tools/before-test.cmd
  tools/run-nrtest.cmd
Labels: enhancement, testing

#392 Add search for SUT exe location
  tools/before-test.cmd
  tools/run-nrtest.cmd
Labels: enhancement, testing
